#!/bin/sh
# Author: Mat Allen
# Description: Look up word definitions at google.com using the Wayback Machine
# Example: google hologram
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Look up word definitions at google.com using the Wayback Machine
Example:
  google hologram
  # w3_browse_url "https://web.archive.org/web/20240000000000*/google.com"
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://web.archive.org/web/20240000000000*/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://web.archive.org/web/20240000000000*/${escaped_args}"
fi
