#!/bin/sh
# Author: Mat Allen
# codecademy: search		-- Search for specific topics on Codecademy
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search terms]...
Description:
  Search for specific topics on Codecademy
Example:
  codecademy linear regression
  'Discover how to use linear regression to analyze data...'
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.codecademy.com/search"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.codecademy.com/search?query=${escaped_args}"
fi