#!/bin/sh
# Author: Mat Allen
# elvis: dictionary		-- Look up word definitions at www.dictionary.com
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Look up word definitions at www.dictionary.com
Example:
  dictionary hologram
  'noun Optics. a negative produced by exposing a high-resolution photographic plate...'
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.dictionary.com/browse/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.dictionary.com/browse/${escaped_args}"
    # w3_browse_url "http://www.etymonline.com/?search=${escaped_args}"
fi
