#!/bin/sh
# Author: [Your Name]
# docker-recipes: search  -- Look up recipes on docker.recipes
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search for recipes on docker.recipes
Example:
  docker-recipes backups
  Search results for "backups" on docker.recipes
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://docker.recipes/search?q="
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://docker.recipes/search?q=${escaped_args}"
fi