#!/bin/sh
# Author: Mat Allen
# hn.algolia: algolia		-- Search for articles on Hacker News
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search for articles on Hacker News
Example:
  algolia play
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://hn.algolia.com/?q="
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://hn.algolia.com/?q=${escaped_args}"
fi