#!/bin/sh
# Author: Mat Allen
# lesswrong: search    -- Look up discussions at www.lesswrong.com
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search terms]...
Description:
  Look up discussions at www.lesswrong.com
Example:
  lesswrong Carlsmith's scheming report
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.lesswrong.com/search?query="
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.lesswrong.com/search?query=${escaped_args}"
fi