#!/bin/sh
# Author: Mat Allen
# google-maps: mapping		-- Search and view maps on Google Maps
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [location]...
Description:
  Search and view maps on Google Maps
Example:
  mapping New York
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.google.com/maps?hl=en"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.google.com/maps?hl=en&q=${escaped_args}"
fi