#!/bin/sh
# Author: Mat Allen
# omniSearch: omnisearch	-- Search via self-hosted OmniSearch (localhost:5000)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search-string]
Description:
  Search via self-hosted OmniSearch metasearch engine
Example:
  omniSearch drone build guide
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://localhost:5000"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://localhost:5000/search?q=${escaped_args}"
fi
