#!/bin/sh
# Author: Mat Allen
# reddit: learnprogramming		-- Search for posts on r/learnprogramming subreddit
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search terms]...
Description:
  Search for posts on the r/learnprogramming subreddit on Reddit
Example:
  learnprogramming git tips
  'A collection of helpful git tips for beginners and experienced programmers...'
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.reddit.com/search/?q=r/learnprogramming"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.reddit.com/search/?q=r/learnprogramming${escaped_args}"
    # w3_browse_url "http://www.etymonline.com/?search=${escaped_args}"
fi
