#!/bin/sh
# Author: Mat Allen
# semanticscholar: search		-- Search for academic papers on Semantic Scholar
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search terms]...
Description:
  Search for academic papers on Semantic Scholar
Example:
  search hypernetworks
  - Shows a list of academic papers related to hypernetworks
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.semanticscholar.org/search?q="
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.semanticscholar.org/search?q=${escaped_args}&sort=relevance"
fi