#!/bin/sh
# Author: Sunday
# elvis: thesaurus -- Look up synonyms at www.thesaurus.com
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Look up synonyms at www.thesaurus.com
Example:
  thesaurus hologram
  'good, adjective as in pleasant, fine..'
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.thesaurus.com/browse/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.thesaurus.com/browse/${escaped_args}"
    # w3_browse_url "http://www.etymonline.com/?search=${escaped_args}"
fi
